# Generated by Django 5.1.2 on 2025-11-14 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код тарифа')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('entry_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма вступительного взноса')),
                ('green_bonus_percent', models.IntegerField(default=50, verbose_name='Процент зеленого бонуса')),
                ('yellow_bonus_percent', models.IntegerField(default=50, verbose_name='Процент желтого бонуса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['entry_amount'],
            },
        ),
        migrations.CreateModel(
            name='StructureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Позиция')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_nodes', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure_node', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mlm.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Узел структуры',
                'verbose_name_plural': 'Узлы структуры',
                'ordering': ['level', 'position'],
                'unique_together': {('parent', 'position')},
            },
        ),
    ]
